### ISSUE TITLE
ESP07 Module PCB View

### ISSUE THREAD

**Issue by jellyfishcoder** [ydonnelly/ESP8266_fritzing#12] opened 2016-06-10 18:33 UTC
In PCB view for ESP07, the labels (and mappings) for gpis 4 and 5 are switched.

**Comment by edelrosespol** [comment] 2019-04-29 19:51
Same problem found, but it was not updated.

**Comment by Damian-R-Smith** [comment] 2019-05-02 15:23
There is an open pull request submitted in march which looks to have addressed this issue. 

https://github.com/ydonnelly/ESP8266_fritzing/pull/13

**Comment by ydonnelly** [comment] 2019-05-03 08:34
Pull request #13 now merged, let me know if the issue is resolved on your end.

**Closed as completed** 2019-07-24 09:22 UTC
